package com.example.birdsofafeather.db.session;


import static androidx.room.OnConflictStrategy.REPLACE;

import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;

import java.util.List;

@Dao
public interface SessionsDao {

    @Query("SELECT * FROM sessions WHERE id=:sessionId")
    Session getForId(int sessionId);

    @Query("SELECT * FROM sessions")
    List<Session> getAll();

    //returns the autogenerated id
    @Insert(onConflict = REPLACE)
    long insert(Session session);

    @Delete
    void delete(Session session);
}
